name: wildfire
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - pillow
  - pytorch
  - torchvision
  - scikit-learn
  - seaborn
  - pip:
      - tfrecord
      - transformers